# Generated by Django 3.1.7 on 2021-02-23 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalyear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='daterange',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='daterange',
            name='name',
        ),
        migrations.AddField(
            model_name='daterange',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
