# Generated by Django 3.1.7 on 2021-02-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalyear', '0005_auto_20210224_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_img', to='fiscalyear.food'),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
