# Generated by Django 3.1.7 on 2021-02-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalyear', '0006_auto_20210225_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
